apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-postgres-configmap
  namespace: monitoramento-dev
data:
  POSTGRES_USER: "zabbix"
  POSTGRES_PASSWORD: "zabbix_pwd"
  POSTGRES_DB: "zabbix"
  PGDATA: "/var/lib/postgresql/data/pgdata"
